### ISSUE TITLE
Pointer on "GitHub Organisation" link in header only showing a hand when hovering over the GitHub Icon

### ISSUE THREAD

**Issue by sqamsqam** [gofrs/website#1]
Clicking the link works fine but the pointer does not change to indicate that its a clickable link unless you over the GitHub Icon

![image](https://user-images.githubusercontent.com/1352462/44703981-cdb59280-aaed-11e8-9a67-631dd8c06440.png)

**Comment by theckman** [comment]
I'm not sure there's much I can easily do without forking the theme we use. I generally see the theme choice as being temporary, and I'd love to have someone with more front-end / hugo experience help us build a personalized site.

**Comment by theckman** [comment]
I was wrong, fix incoming. Thank you again for reporting this @sqamsqam.
